### ISSUE TITLE
invalid JSON.stringify

### ISSUE THREAD

**Issue by Sasquire** [felixfong227/e621_helper_tampermonkey#5]
In e621's javascript file the `toJSON` methods of some types are changed. This will cause `JSON.stringify` to return a string that does not always return the same object when input to `JSON.parse`. More information about custom stringify functions can be found on [Mozilla's website](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

`saveOption`, while not currently used, uses `JSON.stringify` without any modification to the custom `toJSON` methods.

To fix this issue, here is some code I have written. If this code could be copywritten, it is licensed under [unlicense](https://unlicense.org/).
```javascript
function remove_toJSON(){
	delete Object.prototype.toJSON;
	delete Date.prototype.toJSON;
	delete String.prototype.toJSON;
	delete Array.prototype.toJSON;
	delete Number.prototype.toJSON;
}
```

**Comment by felixfong227** [comment]
👋 @Sasquire thanks for pointing out the problem.

But I am not sure what's the issue is, are you saying that E621's custom `toJSON` method will modify the behavior of the stock `JSON.parse`'s behavior?

Cuz later on the `saveOption` function would be just be applicable for storing user's preference inside their LocalStorage system 🤔

**Comment by felixfong227** [comment]
Understood, I will take extra precaution when dealing with JSON conversion stuff.

Thanks 😸
